# Generated by Django 4.0.1 on 2022-03-27 18:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=50)),
                ('works', models.CharField(max_length=50)),
                ('clients', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('intro_big_text', models.TextField(blank=True, max_length=200)),
                ('intro_button', models.CharField(max_length=50)),
                ('about_title', models.CharField(blank=True, max_length=100)),
                ('about_text', models.TextField(blank=True, max_length=500)),
                ('works_title', models.CharField(blank=True, max_length=200)),
                ('works_text', models.TextField(blank=True, max_length=500)),
                ('services_title', models.CharField(blank=True, max_length=100)),
                ('services_text', models.TextField(blank=True, max_length=500)),
                ('clients_title', models.CharField(blank=True, max_length=100)),
                ('clients_text', models.TextField(blank=True, max_length=500)),
                ('contact_title', models.CharField(blank=True, max_length=100)),
                ('contact_text', models.CharField(blank=True, max_length=500)),
                ('contact_button', models.CharField(blank=True, max_length=50)),
                ('address_title', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('email_title', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('phone_title', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_name', models.CharField(max_length=50)),
                ('works_kind', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='works/')),
            ],
            options={
                'verbose_name': 'works',
            },
        ),
    ]
