# Generated by Django 4.0.1 on 2022-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50)),
                ('work_kind', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='work/')),
            ],
            options={
                'verbose_name': 'works',
            },
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
