# Generated by Django 4.0.1 on 2022-03-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_work_delete_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'work'},
        ),
    ]
