# Generated by Django 4.0.1 on 2022-03-27 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_work_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
